name: TITAN_MISSION
on: [workflow_dispatch]
jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Full Lifecycle
        run: |
          set -e
          echo "Workspace: $GITHUB_WORKSPACE"
          curl -L "https://github.com/projectdiscovery/nuclei/releases/download/v3.3.0/nuclei_3.3.0_linux_amd64.zip" -o nuclei.zip
          unzip -o nuclei.zip
          chmod +x nuclei
          ./nuclei -version
          ./nuclei -target https://pay.wallet.tg -t cves/ -t exposures/
