
name: TITAN_MISSION
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Vector'
        required: true
        default: '127.0.0.1'
jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Exec
        run: |
          echo "EXECUTING TITAN ARROW ON: ${{ github.event.inputs.target }}"
          nuclei -u ${{ github.event.inputs.target }} -version
